const NOTES = [
  {
    title: "What Are Vector Embeddings?",
    content: `Vector embeddings are numerical representations of data — text, images, audio, or any other content — mapped into a high-dimensional mathematical space. Each piece of content gets converted into an array of floating-point numbers, typically ranging from 768 to 1536 dimensions depending on the model used. The fundamental insight behind embeddings is that semantically similar content ends up geometrically close together in this vector space, while unrelated content is far apart. For example, the words "dog" and "puppy" would have embedding vectors that are very close to each other because they share similar meaning, while "dog" and "spacecraft" would be far apart.

This works not just for single words but for entire paragraphs and documents. A paragraph about machine learning and a paragraph about neural networks would have similar embeddings, even if they don't share many exact words. The process of creating embeddings involves passing text through a neural network that has been trained on massive amounts of data. Models like OpenAI's text-embedding-3-small, Google's Gecko, Cohere's Embed, and open-source alternatives like sentence-transformers all serve this purpose. These models have learned to capture meaning, context, tone, and relationships between concepts during their training phase. The quality of embeddings depends heavily on the model — larger models generally produce better representations but are slower and more expensive.

Embeddings are the foundation of many modern AI applications. They power semantic search, which finds content by meaning rather than exact keyword matches. They enable RAG (Retrieval-Augmented Generation) systems, where relevant documents are retrieved and fed to an LLM. They drive recommendation engines — Netflix and Spotify use embeddings to suggest content similar to what you've enjoyed. They're used in clustering and classification tasks, anomaly detection, and duplicate detection. Without embeddings, most of the "intelligent" search and retrieval features we see in modern applications would not be possible. The key tradeoff when choosing an embedding model is between quality and cost — OpenAI's text-embedding-3-small costs $0.02 per million tokens and produces 1536-dimensional vectors, while their larger model produces better embeddings but costs more.`,
  },
  {
    title: "RAG (Retrieval-Augmented Generation) Explained",
    content: `RAG, or Retrieval-Augmented Generation, is an AI architecture pattern that combines the power of large language models with external knowledge retrieval. Instead of relying solely on what an LLM memorized during training — which can be outdated, incomplete, or simply wrong — RAG first searches a knowledge base for relevant information and then feeds that context into the LLM along with the user's question. This dramatically improves the accuracy of responses, reduces hallucinations, and allows the system to answer questions about proprietary or recent data that the LLM was never trained on.

The RAG pipeline works in three main steps. First, when a user asks a question, the system converts that question into a vector embedding using the same model that was used to embed the documents. Second, it performs a similarity search against a database of pre-embedded document chunks to find the most relevant pieces of information — typically the top 5 to 20 chunks. Third, those retrieved chunks are injected into the LLM's prompt as context, and the LLM generates a response grounded in that retrieved information. This is why it's called "retrieval-augmented" — the generation is augmented by retrieved data. Companies like Notion, Stripe, Shopify, and Replit use RAG to power their AI assistants and documentation search.

The biggest challenge with RAG is chunking strategy — how you split your documents into pieces for embedding. Chunk too large and you dilute the relevance signal with irrelevant text; chunk too small and you lose important context. Most production systems use overlapping chunks of 500 to 1000 tokens, where each chunk shares some text with the previous one to preserve context at boundaries. Metadata filtering is another important technique — tagging chunks with source, date, author, or category lets you narrow the search space before doing similarity matching. There's also the "lost in the middle" problem where LLMs tend to pay more attention to information at the beginning and end of their context window, ignoring content in the middle. Despite these challenges, RAG remains the most practical and cost-effective approach for building AI applications that need access to specific, current, or proprietary knowledge — far easier than fine-tuning a model.`,
  },
  {
    title: "What is MCP (Model Context Protocol)?",
    content: `MCP, or Model Context Protocol, is an open standard developed by Anthropic that defines how AI models connect to external tools, data sources, and services. Think of it as a universal adapter for AI — instead of building custom integrations for every tool an AI assistant needs to use, MCP provides a standardized way for AI applications to discover and interact with any MCP-compatible service. It's been compared to what USB did for hardware peripherals or what REST APIs did for web services. Before MCP, if you wanted Claude to interact with GitHub, Slack, and your database, you'd need three separate custom integrations. With MCP, each of those services just needs one MCP server, and any MCP-compatible AI client can use them all.

The architecture of MCP involves three main components: the Host (the AI application, like Claude Desktop or an IDE like Cursor), the Client (a protocol layer that manages the connection and message routing), and the Server (a lightweight service that exposes specific tools, resources, or data). An MCP server declares what capabilities it offers through a well-defined JSON schema — what tools are available, what parameters they accept, what resources can be read, and what data formats are supported. The host application discovers these capabilities at connection time and makes them available to the AI model during conversations. For example, an MCP server for GitHub might expose tools like "create_pull_request," "list_issues," "search_code," and "get_file_contents."

The implications of MCP for the AI ecosystem are significant. It creates a network effect — every new MCP server becomes immediately available to every MCP-compatible client, and vice versa. Tool providers build one MCP server instead of separate plugins for ChatGPT, Claude, Gemini, and every other AI platform. The protocol supports production features like authentication, streaming responses, pagination, error handling, and resource subscriptions. The ecosystem is growing rapidly with community-built servers for databases (PostgreSQL, MongoDB), productivity tools (Notion, Linear, Jira), communication platforms (Slack, Discord, email), cloud services (AWS, GCP), and developer tools (GitHub, GitLab, Docker). As adoption increases, AI assistants become capable of interacting with virtually any digital tool through a single standardized interface.`,
  },
  {
    title: "Fine-Tuning vs Prompt Engineering",
    content: `Fine-tuning and prompt engineering are two fundamentally different approaches to customizing the behavior of large language models. Understanding when to use each is critical for building effective AI applications, and getting this decision wrong can waste significant time and money. Prompt engineering involves crafting the input text to guide the model's output without changing the model itself. Fine-tuning involves actually training the model on additional data to permanently alter its weights, behavior, and knowledge patterns. Both have their place, and many production systems use a combination of the two.

Prompt engineering is the simpler and more accessible approach. It includes techniques like few-shot prompting (providing examples of desired input-output pairs in the prompt), chain-of-thought reasoning (asking the model to think step by step before answering), system messages (setting the model's persona, rules, and constraints), and structured output formatting (asking for JSON, markdown, or specific templates). The advantages are significant: no training required, instant iteration, works with any model via API, costs nothing beyond the API call, and you can switch models easily. The downsides are that prompts consume tokens from the context window, complex behaviors can be unreliable through prompting alone, and you're limited by the model's pre-trained knowledge.

Fine-tuning involves taking a pre-trained model and training it further on a curated dataset of input-output pairs using supervised learning. The model adjusts its internal weights to better replicate the patterns in your training data. Fine-tuning is most valuable when you need the model to adopt a very specific writing style consistently, follow complex formatting rules without lengthy prompts, handle specialized domain terminology (medical, legal, financial), or reduce token usage since fine-tuned models need shorter prompts to behave correctly. The practical rule of thumb: always start with prompt engineering — it's faster, cheaper, and often sufficient. Move to fine-tuning when prompts can't achieve the consistency you need, when you have hundreds of high-quality training examples, or when reducing per-request token costs matters at scale. Important caveat: fine-tuning does not reliably add new factual knowledge to a model. For grounding responses in specific data, RAG is almost always the better approach.`,
  },
  {
    title: "How LLM Inference Works — GPUs, Tokens, and Latency",
    content: `When you send a message to ChatGPT or Claude, a complex computational process called inference happens on powerful GPU clusters in data centers. Understanding how this works helps you make better architectural decisions when building AI applications — from choosing the right model to optimizing costs and latency for your users. The process involves tokenization, matrix multiplication across billions of parameters, and autoregressive token generation, all orchestrated across multiple GPUs.

The inference process starts with tokenization — your input text is broken into tokens, which are subword units that the model understands. "Artificial intelligence" might become ["Art", "ificial", " intellig", "ence"]. Each token maps to a number, and these numbers are what the model actually processes. Most models have a context window measured in tokens — GPT-4 supports 128K tokens, Claude supports 200K tokens, Gemini supports up to 1M tokens. More tokens in the input means more computation and higher cost, since API pricing is typically per-token for both input and output. A rough rule of thumb is that 1 token is approximately 4 characters of English text.

The model generates output one token at a time in a process called autoregressive generation — each new token is predicted based on all the tokens that came before it (both your input and the tokens generated so far). This is why you see text streaming in character by character rather than appearing all at once. Each token generation requires a forward pass through billions of parameters using massive matrix multiplications, which is why GPUs (designed for parallel math) are essential. Latency has two components: time-to-first-token (TTFT), which depends on processing the entire input, and tokens-per-second throughput for the output. Longer inputs mean higher TTFT. Techniques like KV-caching (storing intermediate computations to reuse them), prompt caching (reusing embeddings for repeated prompt prefixes), and speculative decoding (using a smaller model to draft tokens that the large model verifies) are all used to reduce latency in production. Companies like Groq and Cerebras are building custom inference chips — called LPUs and wafer-scale engines — that are 5-10x faster than traditional GPU setups for LLM inference.`,
  },
  {
    title: "Compound Interest — The 8th Wonder of the World",
    content: `Compound interest is the process where interest is calculated not just on the initial principal amount, but also on the accumulated interest from previous periods. This creates exponential growth over time, which is why Albert Einstein reportedly called it the eighth wonder of the world. The mathematical formula is A = P(1 + r/n)^(nt), where P is the principal, r is the annual interest rate, n is the number of times interest compounds per year, and t is the number of years. While the formula looks simple, the results over long periods are staggering and deeply counterintuitive to most people.

Here's what makes compound interest so powerful: $10,000 invested at 7% annually (roughly the historical average of the S&P 500 after inflation) becomes $19,672 in 10 years, $38,697 in 20 years, and $76,123 in 30 years. Notice that the last decade alone added $37,426 — more than the first two decades combined. This exponential curve is why starting early matters enormously. A 25-year-old who invests $500 per month at 7% annual returns will have approximately $1.2 million by age 65. A 35-year-old doing the exact same thing will only accumulate about $567,000. That 10-year head start nearly doubles the final amount, even though the 25-year-old only contributed $60,000 more in total. This is the most compelling argument for starting to invest as early as possible, even with small amounts.

Compound interest works against you too, and understanding this is just as important. Credit card debt at 20% APR compounds rapidly — a $5,000 balance making only minimum payments could take 20+ years to pay off and cost over $8,000 in interest alone. Student loans, car loans, and mortgages all involve compound interest working in the lender's favor. The general financial principle is straightforward: make compound interest work for you (investments, savings accounts, retirement funds) and minimize situations where it works against you (high-interest debt, especially credit cards). The order of financial priority for most people should be: build an emergency fund, pay off high-interest debt, then start investing for compound growth as early and consistently as possible.`,
  },
  {
    title: "Index Funds vs Individual Stocks",
    content: `An index fund is a type of investment fund that tracks a specific market index — like the S&P 500, which represents the 500 largest publicly traded US companies. Instead of trying to pick individual winning stocks, you buy a small piece of all 500 companies at once for a single low price. Warren Buffett famously bet $1 million in 2007 that an S&P 500 index fund would outperform a curated collection of hedge funds over 10 years — and he won decisively. The hedge funds returned about 36% over the decade while the index fund returned 125%. This wasn't a fluke — the data consistently shows that passive index investing beats active stock picking.

Over any 15-year period in market history, roughly 90% of actively managed funds — run by professional investors with teams of analysts, proprietary data, and sophisticated models — underperform their benchmark index. Index funds win for three key reasons. First, low fees: index funds charge 0.03% to 0.10% per year (called the expense ratio), while actively managed funds charge 0.50% to 2.00%. That fee difference compounds dramatically over decades. Second, broad diversification: owning 500 companies means any single company's failure barely affects your portfolio. Third, tax efficiency: index funds trade less frequently, generating fewer taxable events. The three most popular S&P 500 index funds are Vanguard's VOO (0.03% expense ratio), Fidelity's FXAIX (0.015%), and Schwab's SWPPX (0.02%).

Individual stock picking isn't inherently bad — it can produce much higher returns if you pick the right companies. Early investors in Apple, Amazon, or Nvidia saw returns that dwarf any index fund. The problem is that picking winners consistently is extraordinarily difficult, and the downside of picking losers is devastating to a portfolio. The behavioral challenge is also significant — when a stock drops 40%, most individual investors panic-sell at the bottom instead of holding or buying more. Most financial advisors recommend making index funds the core of your portfolio (80-90%) and allocating a small "play money" portion (10-20%) to individual stocks if you enjoy researching companies. This way you get the reliable long-term growth of the market while still having the opportunity to outperform with your best ideas.`,
  },
  {
    title: "What is Dollar Cost Averaging?",
    content: `Dollar cost averaging (DCA) is an investment strategy where you invest a fixed dollar amount at regular intervals — for example, $500 on the 1st of every month into an S&P 500 index fund — regardless of whether the market is up, down, or sideways. The key mechanism is automatic: when prices are high, your fixed amount buys fewer shares, and when prices are low, it buys more shares. Over time, this mathematically averages out your cost per share and completely removes the emotional decision-making from investing. You never have to agonize over whether "now is a good time to invest."

The opposite approach is lump sum investing — putting all available money into the market at once. Academic studies, including a famous Vanguard analysis, show that lump sum investing outperforms DCA about 66% of the time, simply because markets tend to go up over time, so investing earlier captures more growth. However, the 34% of the time when DCA wins tends to be during market downturns — exactly when the psychological pain of investing a lump sum is highest. If you received a $60,000 bonus and invested it all the day before a 30% market crash, you'd be down $18,000 immediately. DCA would have spread that investment over months, buying much of it at lower prices. The math slightly favors lump sum, but the psychology strongly favors DCA.

In practice, most working people are already dollar-cost averaging without realizing it — every paycheck that contributes to a 401(k) or automatic investment is DCA by definition. The strategy is most useful when you have a large sum to invest and feel anxious about market timing. A common compromise is to invest half as a lump sum immediately and DCA the other half over 3-6 months. The most important principle underlying DCA is that time in the market beats timing the market. Whether you DCA or lump sum, consistently investing over long periods will almost certainly produce strong returns. The worst strategy is keeping money in cash "waiting for the right time" — most people who do this end up waiting forever and missing years of compounding growth.`,
  },
  {
    title: "How Credit Scores Work",
    content: `A credit score is a three-digit number ranging from 300 to 850 that represents your creditworthiness — essentially a prediction of how likely you are to repay borrowed money on time. The most widely used scoring model is FICO, which is used by approximately 90% of US lenders when making credit decisions. Your credit score directly affects the interest rates you're offered on mortgages, auto loans, credit cards, and even whether you're approved for an apartment lease or certain jobs. The difference between a 750 score and a 650 score on a 30-year mortgage can mean tens of thousands of dollars in additional interest payments.

Your FICO score is calculated from five weighted factors. Payment history (35% of your score) tracks whether you've paid bills on time — even a single 30-day late payment can drop your score 50-100 points and stays on your report for 7 years. Credit utilization (30%) measures how much of your available credit you're using — if you have $10,000 in credit limits and $3,000 in balances, your utilization is 30%. Experts recommend keeping this below 10% for the best scores. Length of credit history (15%) considers the average age of your accounts — this is why closing old credit cards can actually hurt your score. Credit mix (10%) looks at the variety of account types — having both revolving credit (credit cards) and installment loans (auto, student, mortgage) helps. New credit inquiries (10%) tracks how many times you've applied for credit recently — too many applications in a short period signals desperation to lenders.

The most impactful things you can do to build and maintain a strong credit score are straightforward: pay every bill on time without exception, keep credit card balances low relative to your limits, don't close old accounts, and don't apply for credit you don't need. For someone building credit from scratch, the easiest path is to open a starter credit card (or secured card if you can't qualify for a regular one), use it for small recurring purchases like a streaming subscription, and pay the full balance every month. Within 6-12 months of responsible use, you'll have a solid credit foundation. One common misconception is that carrying a balance helps your score — it absolutely does not. Paying in full every month is always better for both your score and your wallet.`,
  },
  {
    title: "The Feynman Technique for Learning",
    content: `The Feynman Technique is a learning method named after Richard Feynman, the Nobel Prize-winning physicist known for his extraordinary ability to explain complex topics in simple terms. The core principle is deceptively simple: if you can't explain something in plain, jargon-free language that anyone could understand, you don't truly understand it yourself. Most people confuse recognition with understanding — they read something, it seems familiar, and they assume they've learned it. The Feynman Technique exposes this illusion by forcing you to actively reconstruct knowledge from scratch.

The technique follows four steps. First, choose a specific concept you want to learn or deepen your understanding of — something concrete like "how does HTTPS encryption work" rather than a vague topic like "security." Second, write an explanation of that concept as if you were teaching it to a bright 12-year-old. Use simple words, avoid technical jargon, draw analogies to everyday things, and include concrete examples. If HTTPS is like sending a letter, the public key is like a padlock you send to someone so they can lock a box that only you can open. Third, identify the gaps — the places in your explanation where you got stuck, resorted to hand-waving, or fell back on jargon because you couldn't think of a simpler way to say it. These gaps are precisely the parts you don't actually understand. Fourth, go back to the source material, study specifically those gaps, and then revise your explanation to be even simpler and more complete.

The power of the Feynman Technique lies in how it leverages active recall and elaborative encoding — two of the most effective learning strategies identified by cognitive science research. When you try to explain something, your brain has to retrieve the information from memory (active recall), organize it into a logical narrative, connect it to other concepts (elaboration), and identify what's missing. This process creates much stronger neural pathways than passive re-reading or highlighting. Studies consistently show that teaching others — or even pretending to teach — produces significantly better long-term retention than any passive review method. The Feynman Technique pairs especially well with spaced repetition: first use Feynman to build deep understanding, then use spaced repetition flashcards to maintain that understanding over time.`,
  },
  {
    title: "Spaced Repetition and Memory",
    content: `Spaced repetition is a learning technique based on reviewing information at systematically increasing intervals over time. It exploits one of the most well-established findings in cognitive psychology: the spacing effect, first documented by Hermann Ebbinghaus in 1885. Ebbinghaus discovered the "forgetting curve" — after learning something new, your memory of it decays exponentially unless you review it. But each review strengthens the memory and slows the decay, so you can wait longer before the next review. The optimal time to review is right at the point when you're about to forget — too early and the review is wasted effort with minimal strengthening, too late and you essentially have to relearn from scratch.

Modern spaced repetition software like Anki automates this scheduling using algorithms based on your performance. When you review a flashcard and answer correctly, the interval before you see it again increases — from 1 day to 3 days to 7 days to 21 days to 60 days and beyond. If you answer incorrectly, the interval resets to a short period so you can relearn the material. The most widely used algorithm is SM-2 (SuperMemo 2), which adjusts intervals based on a per-card "ease factor" that tracks how difficult you find each piece of information. Over time, well-known cards fade into very long intervals (months between reviews) while difficult cards appear more frequently. Medical students are perhaps the most dedicated users of spaced repetition — the average med student maintains 15,000 to 30,000 Anki flashcards covering anatomy, pharmacology, pathology, and clinical medicine. Many credit Anki with getting them through their board exams.

The key to effective spaced repetition is making good flashcards, which is harder than it sounds. The most important rules: one atomic concept per card (don't cram multiple facts into one card), use active recall format (questions, not statements — "What is the capital of France?" not "The capital of France is Paris"), include context and cues to avoid orphaned facts, and use images when possible since visual memory is stronger than textual memory. Spaced repetition is most effective for factual, discrete knowledge — vocabulary, formulas, definitions, anatomy, historical dates, and procedures. For deeper conceptual understanding, it should be combined with techniques like the Feynman method or deliberate practice. The combination of Feynman (for initial deep understanding) plus spaced repetition (for long-term retention) is arguably the most powerful general-purpose learning stack available.`,
  },
  {
    title: "Second Brain Methodology (CODE Framework)",
    content: `The Second Brain methodology, created by productivity expert Tiago Forte, is a personal knowledge management system designed to help you capture, organize, and use the enormous amount of information you encounter daily. The core problem it solves is that our biological brains are excellent at generating ideas and making connections, but terrible at storing and retrieving specific information reliably. We read hundreds of articles, watch countless videos, and have thousands of conversations, but when we need a specific piece of information months later, it's gone. A Second Brain is an external, digital system that handles storage and retrieval so your biological brain can focus on thinking and creating.

The framework is organized around the acronym CODE: Capture, Organize, Distill, Express. Capture means saving anything that resonates with you — articles, highlights, ideas, quotes, images, voice memos — into a single trusted system like Notion, Obsidian, or a note-taking app. The key is to be selective: only capture things that genuinely surprise you, are useful for a current project, or deeply resonate personally. Organize follows the PARA method — Projects (active goals with deadlines), Areas (ongoing responsibilities), Resources (topics of interest), and Archive (inactive items). The counterintuitive insight is that you organize by actionability, not by topic. A note about machine learning goes in your "AI Product Launch" project folder, not in a generic "Machine Learning" topic folder, because you want to find it when you're working on that project.

Distill means progressively summarizing your notes so the key insights are immediately visible without re-reading the entire original source. Forte calls this "progressive summarization" — on your first pass, you bold the most important sentences. On your second pass (which only happens when you revisit the note for a project), you highlight the most important of the bolded text. On a third pass, you write a brief executive summary at the top. This layered approach means you invest more effort only in notes that prove useful over time. Express is the final and most important step — using your collected and distilled knowledge to create something new: articles, presentations, projects, decisions, conversations. The whole philosophy is that knowledge is only valuable when it leads to action and output. The most common failure mode of personal knowledge systems is over-capturing and under-expressing — people save hundreds of articles but never revisit them, creating a digital graveyard of bookmarks instead of a living, useful knowledge system.`,
  },
];

async function seedNotes() {
  console.log(`Seeding ${NOTES.length} notes...\n`);

  for (let i = 0; i < NOTES.length; i++) {
    const note = NOTES[i];
    console.log(`[${i + 1}/${NOTES.length}] Saving: ${note.title}`);

    try {
      const response = await fetch("http://localhost:3000/api/notes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(note),
      });

      if (!response.ok) {
        const error = await response.json();
        console.error(`  ✗ Failed: ${JSON.stringify(error)}`);
      } else {
        console.log(`  ✓ Saved!`);
      }
    } catch (error) {
      console.error(`  ✗ Error: ${error}`);
    }

    // Small delay to avoid rate limiting from OpenAI
    await new Promise((resolve) => setTimeout(resolve, 1000));
  }

  console.log("\nDone! All notes seeded.");
}

seedNotes();
